### ISSUE TITLE
Alpha0.5: net.neurons() returns an error

### ISSUE THREAD

**Issue by slarson** [openworm/PyOpenWorm#102]
On current run:

```
>>> len(set(net.neurons()))
WARNING:PyOpenWorm.dataObject:A a Python class named "NeuronClass" corresponding to the type URI "http://openworm.org/entities/NeuronClass" couldn't be found.
            You may want to import the module containing the class as well as add additional type
            annotations in order to resolve your objects to a more precise type than DataObject.
WARNING:PyOpenWorm.dataObject:A a Python class named "NeuronClass" corresponding to the type URI "http://openworm.org/entities/NeuronClass" couldn't be found.
            You may want to import the module containing the class as well as add additional type
            annotations in order to resolve your objects to a more precise type than DataObject.
WARNING:PyOpenWorm.dataObject:A a Python class named "NeuronClass" corresponding to the type URI "http://openworm.org/entities/NeuronClass" couldn't be found.
            You may want to import the module containing the class as well as add additional type
            annotations in order to resolve your objects to a more precise type than DataObject.
WARNING:PyOpenWorm.dataObject:A a Python class named "NeuronClass" corresponding to the type URI "http://openworm.org/entities/NeuronClass" couldn't be found.
            You may want to import the module containing the class as well as add additional type
            annotations in order to resolve your objects to a more precise type than DataObject.
WARNING:PyOpenWorm.dataObject:A a Python class named "NeuronClass" corresponding to the type URI "http://openworm.org/entities/NeuronClass" couldn't be found.
            You may want to import the module containing the class as well as add additional type
            annotations in order to resolve your objects to a more precise type than DataObject.
WARNING:PyOpenWorm.dataObject:A a Python class named "NeuronClass" corresponding to the type URI "http://openworm.org/entities/NeuronClass" couldn't be found.
            You may want to import the module containing the class as well as add additional type
            annotations in order to resolve your objects to a more precise type than DataObject.
WARNING:PyOpenWorm.dataObject:A a Python class named "NeuronClass" corresponding to the type URI "http://openworm.org/entities/NeuronClass" couldn't be found.
            You may want to import the module containing the class as well as add additional type
            annotations in order to resolve your objects to a more precise type than DataObject.
WARNING:PyOpenWorm.dataObject:A a Python class named "NeuronClass" corresponding to the type URI "http://openworm.org/entities/NeuronClass" couldn't be found.
            You may want to import the module containing the class as well as add additional type
            annotations in order to resolve your objects to a more precise type than DataObject.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "PyOpenWorm/network.py", line 24, in neurons
    yield x.name()
AttributeError: 'DataObject' object has no attribute 'name'
```

**Comment by slarson** [comment]
@mwatts15 can you look into this?

**Comment by mwatts15** [comment]
This would have to be the result of running "examples/rmgr.py". I would clear the database in this case and reload from WormData.n3.

**Comment by travs** [comment]
Fixing #103 means we have added a test that catches this, but it will be an expected failure until the bug is fixed.

**Comment by travs** [comment]
I'm not getting this error when I run it with a newly-generated db. In fact, I'm not getting anything at all:
```
In [50]: set(net.neurons())
Out[50]: set()
```

This and other methods work though:
```
In [51]: set(net.sensory())
Out[51]: {ASIR, PDA, AQR, ...}
```

**Comment by travs** [comment]
OK, we can get all the neurons in the network by creating a "new" Network:
```python
>>> len(P.Network().neuron())
302
```
But not when the Network is retrieved with `P.Worm().get_neuron_network()` or `P.Worm().neuron_network()`.

**Comment by travs** [comment]
See #117
