### ISSUE TITLE
INSTALL.md instructions missing several dependencies

### ISSUE THREAD

**Issue by cheelee** [openworm/PyOpenWorm#197]
Our installation instructions do not explicitly check for a number of dependencies. For my machine, these were numpy, tables (which in turn requires hdf5 to be supported - brew install hdf5 for me), and jsonpickle. The reason I qualify this with "For my machine" is because I do not remember what I had previously installed via pip, and I had done a "pip install scipy" as a random troubleshoot when encountering problems. The first signs of trouble was when I got this output while trying a fresh install and test of PyOpenWorm:

Successfully installed BTrees-4.0.8 Pint-0.6 SPARQLWrapper-1.6.2 ZConfig-3.0.4 decorator-3.4.0 discover-0.4.0 html5lib-0.999 isodate-0.5.0 libneuroml-0.1.9.1 networkx-1.9 numpydoc-0.5 persistent-4.0.8 pyopenworm pyparsing-2.0.2 rdflib-4.2.0 rdflib-zodb-1.0 requirements-0.1 six-1.9.0 transaction-1.4.3 xlrd-0.9.3 zc.lockfile-1.1.0 zdaemon-4.0.0 zodb-4.1.0 zope.interface-4.1.1
Arya:PyOpenWorm cheelee$ python tests/test.py
Traceback (most recent call last):
  File "tests/test.py", line 7, in <module>
    import neuroml.writers as writers
  File "/usr/local/lib/python2.7/site-packages/neuroml/writers.py", line 2, in <module>
    import numpy as np
ImportError: No module named numpy
Arya:PyOpenWorm cheelee$ pip install numpy

I got out of this pickle via the following steps:

1. pip install numpy
2. brew install hdf5
3. pip install tables
4. pip install jsonpickle

and it is uncertain if pip install scipy did anything.

After this point, I was finally able to run "python tests/test.py" as instructed in INSTALL.md

**Comment by cheelee** [comment]
Quick update of additional information:

1. This resulted from attempting pip install pyopenworm. On my laptop, I had run python setup.py install.
2. I was premature in stating above that "I was finally able to run" ... in fact all the tests fail.
3. This test used the "dev" branch of PyOpenWorm.

**Comment by cheelee** [comment]
Early error output from the tests:

Arya:PyOpenWorm cheelee$ python tests/test.py
Testing with configs: ['tests/test_default.conf', 'tests/test_ZODB.conf']
........ss.....ss.s...................sss...sxux....................x........ss.....ss.s...................sss...sxux....................x..............[PyOpenWorm] Loading data into the graph; this may take several minutes!!
EPyOpenWorm already connected
E..WARNING:rdflib.term:some random string does not look like a valid URI, trying to serialize this will break.
..s....PyOpenWorm already connected
EPyOpenWorm already connected
E**********************************************************************
File "/Users/cheelee/work/OpenWorm/repository/MuscleNeuronSubgroup/PyOpenWorm/tests/../README.md", line 38, in README.md
Failed example:
    P.connect()
Expected nothing
Got:
    PyOpenWorm already connected
**********************************************************************
File "/Users/cheelee/work/OpenWorm/repository/MuscleNeuronSubgroup/PyOpenWorm/tests/../README.md", line 47, in README.md
Failed example:
    net = P.Worm().get_neuron_network()
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest README.md[2]>", line 1, in <module>
        net = P.Worm().get_neuron_network()
      File "./PyOpenWorm/worm.py", line 26, in __init__
        DataObject.__init__(self,**kwargs)
      File "./PyOpenWorm/dataObject.py", line 67, in __init__
        raise Exception("You may need to connect to a database before continuing.")
    Exception: You may need to connect to a database before continuing.
**********************************************************************
File "/Users/cheelee/work/OpenWorm/repository/MuscleNeuronSubgroup/PyOpenWorm/tests/../README.md", line 50, in README.md
Failed example:
    aval = net.aneuron('AVAL')
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest README.md[3]>", line 1, in <module>
        aval = net.aneuron('AVAL')
    NameError: name 'net' is not defined
**********************************************************************

**Comment by cheelee** [comment]
Installation via "python setup.py install" under the same conditions after a "pip uninstall PyOpenWorm" resulted in a partially successful test. I'll also note that the post-installation tasks (of populating the database?) does not appear to have taken place when following the installation instructions for "pip install pyopenworm":

Using /usr/local/lib/python2.7/site-packages
Finished processing dependencies for PyOpenWorm==0.5.3
Running post-install script(s)
Running insert_worm.py as UID 501
uploaded neurons
uploaded muscles
uploaded lineage and descriptions
uploaded connections
uploaded receptors, innexins, neurotransmitters and neuropeptides
uploaded types
serialized to n3 file
copying /Users/cheelee/work/OpenWorm/repository/MuscleNeuronSubgroup/PyOpenWorm/OpenWormData/scripts/worm.db to /usr/local/lib/python2.7/site-packages/PyOpenWorm-0.5.3-py2.7.egg/PyOpenWorm
copying /Users/cheelee/work/OpenWorm/repository/MuscleNeuronSubgroup/PyOpenWorm/OpenWormData/scripts/worm.db.index to /usr/local/lib/python2.7/site-packages/PyOpenWorm-0.5.3-py2.7.egg/PyOpenWorm
copying /Users/cheelee/work/OpenWorm/repository/MuscleNeuronSubgroup/PyOpenWorm/OpenWormData/scripts/worm.db.lock to /usr/local/lib/python2.7/site-packages/PyOpenWorm-0.5.3-py2.7.egg/PyOpenWorm
copying /Users/cheelee/work/OpenWorm/repository/MuscleNeuronSubgroup/PyOpenWorm/OpenWormData/scripts/worm.db.tmp to /usr/local/lib/python2.7/site-packages/PyOpenWorm-0.5.3-py2.7.egg/PyOpenWorm
Arya:PyOpenWorm cheelee$ python tests/test.py
Testing with configs: ['tests/test_default.conf', 'tests/test_ZODB.conf']
........ss.....ss.s...................sss...sxux....................x........ss.....ss.s...................sss...sxux....................x..............[PyOpenWorm] Loading data into the graph; this may take several minutes!!
...s..x..s.......WARNING:rdflib.term:some random string does not look like a valid URI, trying to serialize this will break.
..s.......
----------------------------------------------------------------------
Ran 179 tests in 214.119s

OK (skipped=21, expected failures=7, unexpected successes=2)

**Comment by cheelee** [comment]
This is probably caused by my attempts to install PyOpenWorm over global pip packages. They have gone away once I've restarted this process via virtualenv. Should be safe to close this issue and chalk it up to me being dumb.
